#!/bin/sh

crl=`curl -s "https://api.openweathermap.org/data/2.5/weather?q=$1&appid=9c00858d64ac723c0a3e6fa48b66663b&units=metric" | jq '.main.temp'`

temp=$(echo "scale=2;((9/5) * $crl) + 32" |bc)

city=$(echo $1 | sed 's/ /\\ /g')

curl -XPOST http://INFLUXDB:8086/write?db=qe1 --data-binary "weather,city=$city temperature=$temp $2"

echo $temp
