#!/bin/sh
crl=`curl -s "https://api.openweathermap.org/data/2.5/weather?q=$1&appid=<API KEY>&units=imperial" | jq '.main.temp'`
curl -XPOST http://INFLUXDB:8086/write?db=qe1 --data-binary "weather,city=$1 temperature=$crl $2"
echo $crl
